import Footer from "@/components/Footer";
import Nav from "@/components/Nav";
import Provider from "@/components/Provider";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-anuphan">
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <div className="relative z-10">
            <Nav />
            <main className="app">{children}</main>
            <Footer />
          </div>
        </Provider>
      </body>
    </html>
  );
}
